### ISSUE TITLE
Ability to set quantity of items dropped?

### ISSUE THREAD

**Issue by darthvader45** [TheAwesomeGem/BlockDropsTweaker#12]
Any chance we could get the ability to define how many of our drop we want to get from a block?  Currently there's no way to do this, and I'd like to be able to customize this.

**Comment by ghost** [comment]
Take a look here for an simple Redstone example

https://github.com/TheAwesomeGem/BlockDropsTweaker/issues/10#issuecomment-764001154

**Comment by darthvader45** [comment]
Thanks.
